import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedAndroidUIStatusBarWidget14.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedAndroidUIHomeIndicatorWidget24.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedAndroidUIHomeIndicatorWidget25.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedInputFieldWidget8.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedKontenWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedAturTanggalAbsensiWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedInputFieldWidget6.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedTopBarWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedIconCalendarWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedButtonWidget14.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedModalDialogCautionWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedInputFieldWidget5.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedPolygon1Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedInputFieldWidget7.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget1/generated/GeneratedBackgroundWidget2.dart';

/* Frame Pengaturan - Atur Tanggal Absensi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPengaturanAturTanggalAbsensiWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget24(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget25(),
              ),
              Positioned(
                left: -4435.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedInputFieldWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedTopBarWidget2(),
              ),
              Positioned(
                left: 108.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 24.0,
                child: GeneratedAturTanggalAbsensiWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget6(),
              ),
              Positioned(
                left: 24.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget7(),
              ),
              Positioned(
                left: 24.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget8(),
              ),
              Positioned(
                left: 337.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 11.0,
                child: GeneratedPolygon1Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 50.0,
                child: GeneratedKontenWidget1(),
              ),
              Positioned(
                left: 317.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconCalendarWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 56.0,
                child: GeneratedButtonWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBackgroundWidget2(),
              ),
              Positioned(
                left: 48.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 284.0,
                child: GeneratedModalDialogCautionWidget1(),
              )
            ]),
      ),
    ));
  }
}
