import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedBackgroundWidget4.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedInputFieldWidget9.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedIconCalendarWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedAndroidUIStatusBarWidget15.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedAndroidUIHomeIndicatorWidget26.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedInputFieldWidget11.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedInputFieldWidget10.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedAturTanggalAbsensiWidget4.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedTopBarWidget3.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedKontenWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedAndroidUIHomeIndicatorWidget27.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedPolygon1Widget2.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget2/generated/GeneratedInputFieldDatePickerWidget.dart';

/* Frame Pengaturan - Atur Tanggal Absensi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPengaturanAturTanggalAbsensiWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget26(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget27(),
              ),
              Positioned(
                left: -4435.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedInputFieldWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedTopBarWidget3(),
              ),
              Positioned(
                left: 108.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 24.0,
                child: GeneratedAturTanggalAbsensiWidget4(),
              ),
              Positioned(
                left: 24.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget11(),
              ),
              Positioned(
                left: 337.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 11.0,
                child: GeneratedPolygon1Widget2(),
              ),
              Positioned(
                left: 24.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 50.0,
                child: GeneratedKontenWidget2(),
              ),
              Positioned(
                left: 317.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconCalendarWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBackgroundWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 495.0,
                child: GeneratedInputFieldDatePickerWidget(),
              )
            ]),
      ),
    ));
  }
}
