import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedInputFieldWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedAndroidUIStatusBarWidget13.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedAndroidUIHomeIndicatorWidget23.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedKontenWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedIconCalendarWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedAndroidUIHomeIndicatorWidget22.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedInputFieldWidget4.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedInputFieldWidget3.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedInputFieldWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedAturTanggalAbsensiWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedpengaturanaturtanggalabsensiwidget/generated/GeneratedTopBarWidget1.dart';

/* Frame Pengaturan - Atur Tanggal Absensi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPengaturanAturTanggalAbsensiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget22(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget23(),
              ),
              Positioned(
                left: -4435.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedInputFieldWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedTopBarWidget1(),
              ),
              Positioned(
                left: 108.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 24.0,
                child: GeneratedAturTanggalAbsensiWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 60.0,
                child: GeneratedInputFieldWidget4(),
              ),
              Positioned(
                left: 337.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 11.0,
                child: GeneratedPolygon1Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 50.0,
                child: GeneratedKontenWidget(),
              ),
              Positioned(
                left: 317.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconCalendarWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 56.0,
                child: GeneratedButtonWidget12(),
              )
            ]),
      ),
    ));
  }
}
