import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedgroup470widget/generated/GeneratedStaffPegawaiWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedgroup470widget/generated/GeneratedRectangle1539Widget.dart';

/* Group Group 470
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup470Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 1012.0,
        height: 194.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1012.0,
                height: 194.0,
                child: GeneratedRectangle1539Widget(),
              ),
              Positioned(
                left: 77.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 475.0,
                height: 124.0,
                child: GeneratedStaffPegawaiWidget1(),
              )
            ]),
      ),
    ));
  }
}
