import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedFrame8Widget3.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedVektor2Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedAndroidUIHomeIndicatorWidget15.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedRectangle1540Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedVector1Widget2.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedVektor1Widget1.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedEllipse49Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/e_presensiapp/generateddashboardwidget/generated/GeneratedAndroidUIStatusBarWidget8.dart';

/* Frame Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1176.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 941.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(12.0),
                        border: Border.all(
                          width: 16.0,
                          color: Color.fromARGB(255, 186, 192, 202),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(12.0),
                              child: Container(
                                color: Color.fromARGB(255, 253, 254, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 179.0,
                              child: GeneratedFrame2Widget(),
                            ),
                            Positioned(
                              left: 116.5076904296875,
                              top: 39.6925048828125,
                              right: null,
                              bottom: null,
                              width: 262.4731750488281,
                              height: 72.96551513671875,
                              child: GeneratedVector1Widget2(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: -3.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 59.0,
                              child: GeneratedRectangle1540Widget(),
                            ),
                            Positioned(
                              left: -73.0,
                              top: -87.83621215820312,
                              right: null,
                              bottom: null,
                              width: 529.0000610351562,
                              height: 428.67242431640625,
                              child: GeneratedVektor1Widget1(),
                            ),
                            Positioned(
                              left: -810.0,
                              top: -118.0,
                              right: null,
                              bottom: null,
                              width: 1948.0001220703125,
                              height: 1294.0,
                              child: GeneratedVektor2Widget(),
                            ),
                            Positioned(
                              left: 291.0,
                              top: 1061.590087890625,
                              right: null,
                              bottom: null,
                              width: 74.99234008789062,
                              height: 44.59003829956055,
                              child: GeneratedGroup20Widget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 434.0,
                              right: null,
                              bottom: null,
                              width: 345.0,
                              height: 179.0,
                              child: GeneratedFrame7Widget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 635.0,
                              right: null,
                              bottom: null,
                              width: 349.0,
                              height: 222.0,
                              child: GeneratedGroup23Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1157.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 16.0,
                              child: GeneratedAndroidUIHomeIndicatorWidget15(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 873.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 68.0,
                              child: GeneratedGroup21Widget(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 78.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 63.0,
                              child: GeneratedEllipse49Widget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 345.0,
                              height: 254.0,
                              child: GeneratedFrame8Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 25.0,
                              child: GeneratedAndroidUIStatusBarWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
