import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedsplashscreenwidget/generated/GeneratedGroup477Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedsplashscreenwidget/generated/GeneratedAndroidUIStatusBarWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedsplashscreenwidget/generated/GeneratedAndroidUIHomeIndicatorWidget2.dart';

/* Frame Splash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 0.640625],
            colors: [
              Color.fromARGB(255, 0, 24, 89),
              Color.fromARGB(255, 3, 83, 151)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 201.0,
                child: GeneratedGroup477Widget(),
              )
            ]),
      ),
    ));
  }
}
