import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedTabWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedTabWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedRekapAbsensiWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedPilihTanggalWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame13Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame17Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedAndroidUIHomeIndicatorWidget8.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame18Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedGroup453Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedTopBarWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedBifiltersquarefillWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedTabWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedAndroidUIHomeIndicatorWidget7.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame16Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedAndroidUIStatusBarWidget4.dart';
import 'package:flutterapp/e_presensiapp/generatedlihatrekapwidget/generated/GeneratedFrame14Widget.dart';

/* Frame Lihat Rekap
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLihatRekapWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 253, 254, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedTopBarWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 24.0,
                child: GeneratedRekapAbsensiWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 26.0,
                child: GeneratedGroup453Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 19.0,
                child: GeneratedPilihTanggalWidget(),
              ),
              Positioned(
                left: 199.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedBifiltersquarefillWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 48.0,
                child: GeneratedTabWidget(),
              ),
              Positioned(
                left: 252.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 48.0,
                child: GeneratedTabWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 48.0,
                child: GeneratedTabWidget2(),
              ),
              Positioned(
                left: 229.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedButtonWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame12Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame13Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame15Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame14Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame16Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame17Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 59.0,
                child: GeneratedFrame18Widget(),
              )
            ]),
      ),
    ));
  }
}
