import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedAndroidUIHomeIndicatorWidget3.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedAndroidUIStatusBarWidget2.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedEllipse13Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedEllipse15Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedEllipse14Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedAndroidUIHomeIndicatorWidget4.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedBottomSheetDefaultWidget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedVector2Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget1/generated/GeneratedVector1Widget1.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget2(),
              ),
              Positioned(
                left: -101.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 575.0,
                height: 383.0,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 227.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 256.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 86.0,
                child: GeneratedVector2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 261.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 326.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 68.0,
                child: GeneratedEllipse14Widget1(),
              ),
              Positioned(
                left: 141.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedEllipse15Widget1(),
              ),
              Positioned(
                left: 207.0,
                top: -70.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 244.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: -71.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 168.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: -30.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedEllipse13Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 44.0,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 238.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 44.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 116.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 72.0,
                child: GeneratedVector1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 564.0,
                child: GeneratedBottomSheetDefaultWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget4(),
              )
            ]),
      ),
    ));
  }
}
