import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedAndroidUIHomeIndicatorWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedVektor1Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedAndroidUIStatusBarWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/e_presensiapp/generatedloginwidget/generated/GeneratedBottomSheetDefaultWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget(),
              ),
              Positioned(
                left: -101.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 575.0,
                height: 383.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 227.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 256.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 86.0,
                child: GeneratedVector2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 261.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: -71.0,
                top: -70.0,
                right: null,
                bottom: null,
                width: 522.0,
                height: 423.0,
                child: GeneratedVektor1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 564.0,
                child: GeneratedBottomSheetDefaultWidget(),
              )
            ]),
      ),
    ));
  }
}
