import 'package:flutter/material.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedGroup22Widget3.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedModalDialogCautionWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedBackgroundWidget.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedAndroidUIHomeIndicatorWidget14.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedAndroidUIHomeIndicatorWidget13.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedAndroidUIStatusBarWidget7.dart';
import 'package:flutterapp/e_presensiapp/generatedpresensiwidget2/generated/GeneratedFrame8Widget1.dart';

/* Frame Presensi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPresensiWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 16.0,
            color: Color.fromARGB(255, 186, 192, 202),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(12.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAndroidUIStatusBarWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedAndroidUIHomeIndicatorWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 68.0,
                child: GeneratedGroup22Widget3(),
              ),
              Positioned(
                left: 15.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 233.0,
                child: GeneratedFrame8Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 814.0,
                child: GeneratedBackgroundWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 284.0,
                child: GeneratedModalDialogCautionWidget(),
              )
            ]),
      ),
    ));
  }
}
