import 'package:flutter/material.dart';

/* Frame Android Small - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
      ),
    ));
  }
}
